### ISSUE TITLE
libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by ZUBAT** [burnedram/affesay#5]
plugin_load addons/affesay
 failed to dlopen /usr/games/gameservers/csgo_cw/csgo/addons/affesay.so error=/usr/games/gameservers/csgo_cw/bin/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/games/gameservers/csgo_cw/csgo/addons/affesay.so)

**Comment by burnedram** [comment]
Hi ZUBAT, I'm "closing" this repository, as there is nothing of actual value here.

If you're looking for a plugin that can show colored text in player's chat, please take a look at [ColorSay](https://github.com/burnedram/csgo-plugin-color-say)
